import 'package:flutter/material.dart';

List<String> sprueche1 = ['Dein Mut',
  'Dein Lächeln',
  'Deine Kreativität',
  'Dein Wille',
  'Dein Herz',
  'Deine Freundlichkeit',
  'Dein Geist',
  'Deine Neugier',
  'Dein Engagement',
  'Dein Enthusiasmus',
  'Deine Ausdauer',
  'Dein Wissen',
  'Deine Intuition',
  'Deine Begeisterung',
  'Dein Vertrauen',
  'Deine Leidenschaft',
  'Dein Optimismus',
  'Dein Fokus',
  'Dein Humor',
  'Dein Mitgefühl',
  'Deine Inspiration',
  'Deine Geduld',
  'Deine Stärke',
  'Dein Ehrgeiz',
  'Dein Tatendrang',
  'Dein Herzblut',
  'Deine Achtsamkeit',
  'Dein Durchhaltevermögen',
  'Dein Selbstbewusstsein',
  'Dein Teamgeist',
  'Deine Entschlossenheit',
  'Deine Gelassenheit',
  'Dein Ideenreichtum',
  'Dein Fingerspitzengefühl',
  'Deine Sorgfalt',
  'Deine Flexibilität',
  'Deine Empathie',
  'Dein Charisma',
  'Dein Sinn für Schönheit',
  'Deine Träume',
  'Dein Abenteuergeist',
  'Deine Charakterstärke',
  'Dein Erfindergeist',
  'Dein Einfallsreichtum',
  'Dein Wachstum',
  'Deine Kraft',
  'Dein Selbstvertrauen',
  'Deine Entfaltung',
  'Dein Sinn für Humor',
  'Deine Einzigartigkeit',];
List<String> sprueche2 = [ 'erfüllt',
  'öffnet',
  'inspiriert',
  'stärkt',
  'belebt',
  'bereichert',
  'erhellt',
  'motiviert',
  'ermutigt',
  'beflügelt',
  'nährt',
  'weckt',
  'klärt',
  'führt',
  'leitet',
  'beleuchtet',
  'entfaltet',
  'vertieft',
  'erneuert',
  'schützt',
  'erfreut',
  'unterstützt',
  'entzündet',
  'erhebt',
  'erfrischt',
  'erwärmt',
  'bewahrt',
  'gestaltet',
  'schenkt',
  'regt an',
  'eröffnet',
  'initiiert',
  'begleitet',
  'berührt',
  'beglückt',
  'animiert',
  'fokussiert',
  'harmonisiert',
  'entfesselt',
  'stimuliert',
  'erstrahlt',
  'verleiht',
  'entfacht',
  'ergänzt',
  'erweckt',
];
List<String> sprueche3 = [  'deine Träume',
  'deine Ziele',
  'deine Hoffnung',
  'deinen Geist',
  'deine Seele',
  'dein Potenzial',
  'deine Kreativität',
  'dein Glück',
  'dein Selbstvertrauen',
  'deine Leidenschaft',
  'deine Inspiration',
  'deine Stärken',
  'deine Ideen',
  'deinen Willen',
  'dein Herz',
  'deine Vision',
  'deine Motivation',
  'deine Ambitionen',
  'deine Chancen',
  'deine Fähigkeiten',
  'deine Neugier',
  'deine Zukunft',
  'deine Erfolge',
  'deine Gedanken',
  'deine Vorstellungskraft',
  'deine Gelassenheit',
  'deinen Mut',
  'deine Entschlossenheit',
  'deine Harmonie',
  'deine Errungenschaften',
  'deine Lebenskraft',
  'deine Dankbarkeit',
  'deine Freude',
  'deine Wahrnehmung',
  'dein Lächeln',
  'deine Glücksmomente',
  'deine Lernfähigkeit',
  'deine innere Ruhe',
  'deine Überzeugung',
  'deine Ausdauer',
  'dein Kreativpotenzial',
  'deine Ausstrahlung',
  'deine Tatkraft',
  'deine Sicherheit',
  'deine Möglichkeiten',
  'deine Sehnsucht',
  'deine Einzigartigkeit',
  'dein Abenteuerlust',
];
List<String> sprueche4 = [ 'bei jedem Atemzug',
  'in deinem Rhythmus',
  'auf deinem Entdeckungsweg',
  'hinter deinen Gedanken',
  'im Auge des Sturms',
  'in deiner Stille',
  'auf sanften Wellen',
  'in deiner Kraft',
  'im Spiegel deiner Seele',
  'im Klang des Moments',
  'jeden Tag',
  'in jedem Moment',
  'auf deinem Weg',
  'in deinem Herzen',
  'zu jeder Zeit',
  'in deinem Inneren',
  'überall um dich herum',
  'wenn du es am wenigsten erwartest',
  'im richtigen Augenblick',
  'ganz intuitiv',
  'mit Leichtigkeit',
  'in Harmonie',
  'mit Zuversicht',
  'mit Freude',
  'mit Geduld',
  'im Einklang mit dir selbst',
  'auf natürliche Weise',
  'in stillen Augenblicken',
  'mit klarem Bewusstsein',
  'mit positivem Denken',
  'ohne große Anstrengung',
  'mit einem Lächeln',
  'in deinem Tempo',
  'auf einfache Art',
  'ohne Stress',
  'mit offenem Geist',
  'voller Energie',
  'mit tiefem Vertrauen',
  'ohne Zweifel',
  'mit großer Begeisterung',
  'spielerisch',
  'achtsam',
  'voller Inspiration',
  'in Stille',
  'mit klarem Fokus',
  'in reiner Dankbarkeit',
  'voller Hoffnung',
  'mit bewusster Achtsamkeit',
  'in vollen Zügen',
  'auf wunderbare Weise',
];
List<String> sprueche5 = [ '– nutze sie weise.',
  '– glaube daran.',
  '– vertraue darauf.',
  '– öffne dein Herz.',
  '– folge deinem Instinkt.',
  '– genieße den Moment.',
  '– handle mutig.',
  '– bleibe positiv.',
  '– ergreife die Chance.',
  '– bewahre Gelassenheit.',
  '– halte durch.',
  '– bleibe neugierig.',
  '– strebe nach Exzellenz.',
  '– teile deine Freude.',
  '– sei dankbar.',
  '– halte an deinen Träumen fest.',
  '– lass dich nicht aufhalten.',
  '– erkunde Neues.',
  '– höre auf deine innere Stimme.',
  '– zeige Mitgefühl.',
  '– bewahre dein Lächeln.',
  '– schenke Liebe.',
  '– vertraue dir selbst.',
  '– finde dein Gleichgewicht.',
  '– strahle Zuversicht aus.',
  '– bleibe authentisch.',
  '– wachse über dich hinaus.',
  '– bleibe im Fluss.',
  '– erlaube dir zu träumen.',
  '– setze klare Ziele.',
  '– bleibe fokussiert.',
  '– umarme Veränderungen.',
  '– halte den Kurs.',
  '– spreche Mut hinaus.',
  '– verbreite Freundlichkeit.',
  '– finde inspirierende Momente.',
  '– entdecke deine Stärke.',
  '– nähre deine Seele.',
  '– lebe bewusst.',
  '– strahle Freude aus.',
  '– finde dein Glück.',
  '– lebe deinen Traum.',
  '– wachse stetig.',
  '– genieße die Reise.',
  '– vertraue dem Fluss.',
  '– öffne neue Türen.',
  '– entfessele dein Potenzial.',
  '– tanze im Regen.',
  '– schenke dir Zeit.',
  '– strahle Geborgenheit aus.',
];